# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc015fca6883857c8f41bef4d1bb487bc280594426a57d8cb7d5f714739a5158945c36e00a58742bdb5186423d36626d2eeac581ec98ae76888aff0dbd76168e

test:
  secret_key_base: caff3475cc9c28c2135f1acbcdc2fff5cb8952437bb0cc5fba6c00b3a89f70d846b1150a0a1042f4268bf2e405b815bd055c1bb22f12845b7674411e72bd7301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
